name: agrimatch_app
description: AgriMatch mobile app - soil analysis & consultation
publish_to: "none"
version: 0.1.0+1

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.0.5
  http: ^0.13.6
  shared_preferences: ^2.2.3
  image_picker: ^1.0.7
  path_provider: ^2.1.3
  sqflite: ^2.3.3
  flutter_secure_storage: ^9.2.2
  uuid: ^4.5.1  

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^4.0.0
  flutter_launcher_icons: ^0.13.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/

flutter_launcher_icons:
  android: true
  ios: true
  image_path: "assets/images/logo.png"

